name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'  # or pyproject.toml

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tag version
        uses: anothrNick/github-tag-action@v1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
